### ISSUE TITLE
Enable managing kontrolx options with a config file

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/kontrol#73]
It is very error prone to keep in mind what command you just kompiled with, which modules are imported, etc.

Instead of requiring the user to always kompile with certain flags, we should offer a configuration file (similar to how foundry does, which lets you set things like number of retries, etc). If you need to try using different flags here and there that can be managed with profiles.

This is also how Foundry does it, so it would be a recognizable pattern for devs.
(As a small bonus, seeing commited `kontrol.toml` files in Solidity git repos would work as good marketing, the same way you see `Dockerfile`s all over and that immediately tells you "oh this team is using Docker".)

So instead of for example

```
kontrolx foundry-kompile --require "aux-lemmas.k" --module-import PinataTest:AUX-LEMMAS --rekompile --with-llvm-library --verbose --regen
```

and then 

```
kontrolx foundry-prove --max-iterations 50 --verbose --no-break-on-calls --test PinataTest.testA0 --max-depth 1000
```

we could have a file `kontrol.toml`:

```toml
[profile.a0]
test = 'PinataTest.testA0'
max-depth = 1000

kompile-require = [ 'aux-lemmas.k' ]
kompile-module-import = [ 'PinataTest:AUX-LEMMAS' ]
kompile-llvm-library = true

prove-max-iterations = 50
prove-break-on-calls = false
```

This would likely reduce errors due to forgetting a certain flags, and improve reproducibility since every engineer should be able to get the same result by just doing 

```
kontrolx foundry-prove --profile a0
```

The best order of priority is probably

1. command-line flags
2. config file
3. defaults
