### ISSUE TITLE
Support multiple tests in `kontrol.toml`

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#734]
As identified by @anvacaru, `kontrol.toml` currently doesn't allow specification of several values for `--match-test` or `--mt`. We should add support for specification of different prefixes or test names there.

**Comment by anvacaru** [comment]
Closing this as `Not an issue`. In `options.py`, the argument type for `match-test` is defined as [list_of(parse_test_version_tuple)](https://github.com/runtimeverification/kontrol/blob/master/src/kontrol/options.py#L419).

This TOML example is already supported. 
```toml
[build.default]
foundry-project-root       = '.'
regen                      = false
rekompile                  = false
verbose                    = false
debug                      = false
require                    = 'lemmas.k'
module-import              = 'TestBase:KONTROL-LEMMAS'

[prove.default]
foundry-project-root       = '.'
verbose                    = false
debug                      = false
max-depth                  = 25000
reinit                     = false
cse                        = false
workers                    = 4
failure-information        = true
counterexample-information = true
minimize-proofs            = false
fail-fast                  = true
smt-timeout                = 1000
break-every-step           = false
break-on-jumpi             = false
break-on-calls             = false
break-on-storage           = false
break-on-basic-blocks      = false
break-on-cheatcodes        = false
run-constructor            = false
match-test                 = ['CounterTest.test_Increment', 'testFuzz_SetNumber:0']

[show.default]
foundry-project-root       = '.'
verbose                    = true
debug                      = false
```
